name: Update ACM Events

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'automation/scripts/fetch_rss.py'
      - '.github/workflows/fetch-acm-events.yml'

jobs:
  fetch-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install feedparser
      
      - name: Fetch ACM events from Dragon Central
        run: |
          python automation/scripts/fetch_rss.py
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet docs/data/events.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add docs/data/events.json
          git commit -m "🤖 Auto-update ACM events from Dragon Central"
          git push
      
      - name: Report status
        if: steps.check_changes.outputs.changed == 'false'
        run: |
          echo "✅ No changes detected - events.json is up to date"
